name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test Hola Mundo
      id: test-hola-mundo
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: Test Hola Mundo
        setup-command: ''
        command: gradle test
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-HOLA-MUNDO_RESULTS: "${{steps.test-hola-mundo.outputs.result}}"
      with:
        runners: test-hola-mundo
